name: "CordCloudJS Action"
description: "GitHub Action JS-Version for CordCloud"
author: "thinkasany"
branding:
  icon: "check-circle"
  color: "gray-dark"
inputs:
  email:
    description: "your cordcloud email"
    required: true
  passwd:
    description: "your cordcloud password"
    required: true
  secret:
    description: "your 2 step secret"
    required: false
  host:
    description: "base host"
    required: false
    default: "cordcloud.us,cordcloud.one,cordcloud.biz,c-cloud.xyz"
outputs:
  result:
    description: "The result of api"
runs:
  using: node16
  main: 'dist/index.js'
